name=SPD_Arduino
version=0.0.2
author=spdrw
maintainer=h13317136163@163.com
sentence=DDR SPD Read/Write.
paragraph=Read and write DDR memory module SPD data via I2C.
category=Sensor
url=https://github.com/spdrw/SPD_Arduino
architectures=*  
includes=SPD_Arduino.h
